### ISSUE TITLE
python 3.6 support

### ISSUE THREAD

**Issue by FlorianLudwig** [Yakifo/amqtt#37]
> Python 3.6.8 is planned to be the last bugfix release for 3.6.x. Following the release of 3.6.8, we plan to provide security fixes for Python 3.6 as needed through 2021, five years following its initial release.

Python 3.6.8 was released 2018-12-24. Since then no bugfix releases were done, only security fixes are provided.

I would drop 3.6 support in the 0.11.x release of aMQTT. What does everyone else think? Objections?

**Comment by HerrMuellerluedenscheid** [comment]
Easy to overlook but there is a python version check in `pub_script.py` and `broker_script.py`. Just dropping this here a s reminder.

**Comment by HerrMuellerluedenscheid** [comment]
`python3.6` dropped in #62
