### ISSUE TITLE
Flake8 on long doc strings

### ISSUE THREAD

**Issue by HerrMuellerluedenscheid** [Yakifo/amqtt#38]
How do we handle long doc string line containing e.g. URLS such as

        Send an MQTT `PUBLISH <http://docs.oasis-open.org/mqtt/mqtt/v3.1.1/os/mqtt-v3.1.1-os.html#_Toc398718037>`_ message and wait for acknowledgment depending on

(taken from `client.py`)

Append `noqa` and end of line or break the URL? I'm not sure what is more common. Opinions?

**Comment by FlorianLudwig** [comment]
`pep8` and `black` disagree on some formatting questions.

So I would vote to disable all style-checks in flake and not run pep8 at all. Style checks are performed by black.

**Comment by HerrMuellerluedenscheid** [comment]
Sounds good. Best to have a single source of truth.
