### ISSUE TITLE
Subscriber not receiving messages from local hbmqtt broker

### ISSUE THREAD

**Issue by mkhare** [Yakifo/amqtt#44]
I am running subscriber to hbmqtdd, which i ran on my local machine, either on 127.0.0.1, or another local ip address,  expected to receive $SYS packets, but simply not receiving them. The same subscriber receives the SYS messages properly from test.mosquitto.org, so the subscriber logic is working ok in that case. If i publish a message to a topic on the local broker, then the subscriber does not receive the message.

Commands used

 C:\Users\madhu\AppData\Local\Programs\Python\Python37\Scripts\hbmqtt_sub --url mqtt://127.0.0.1:1883/  -t '$SYS/#' -q 0

[2021-03-18 00:34:25,582] :: INFO - Finished processing state new exit callbacks.
[2021-03-18 00:34:25,582] :: INFO - Finished processing state connected enter callbacks.

… but nothing else…………………...

 C:\Users\madhu\AppData\Local\Programs\Python\Python37\Scripts\hbmqtt.exe -d

**Comment by mkhare** [comment]
Also - I there a working version that I can use with python 3.7? I just need some stable version for now.

**Comment by FlorianLudwig** [comment]
Hi @mkhare 

I have not yet come around to try to reproduce your problem, sorry.

About releases:
Currently there is no "stable" release of aMQTT. The newest release is `0.10.0-alpha.1`, which can be installed fro PyPI. It runs with python 3.6 to 3.9.

It should be as stable as the last hbmqtt release.

**Comment by mkhare** [comment]
i updated but am getting a granted_qos of 128 on subscribe.. maybe its just some configuration on the broker .. can you suggest

**Comment by mkhare** [comment]
This worked for me, but after changing as follows: 

    Return value for exception from asyncio_gather
    
    The function asyncio_gather was creating an exception for some default
    plugins. Used the positional parameter to return exceptions as True.

diff --git a/hbmqtt/plugins/manager.py b/hbmqtt/plugins/manager.py
index c96c5f1..e4d78c5 100644
--- a/hbmqtt/plugins/manager.py
+++ b/hbmqtt/plugins/manager.py
@@ -180,7 +180,7 @@ class PluginManager:
                         self.logger.error("Method '%r' on plugin '%s' is not a coroutine" %
                                           (coro, plugin.name))
         if tasks:
-            ret_list = yield from asyncio.gather(*tasks, loop=self._loop)
+            ret_list = yield from asyncio.gather(*tasks, loop=self._loop, return_exceptions = True)
             # Create result map plugin=>ret
             ret_dict = {k: v for k, v in zip(plugins_list, ret_list)}
         else:

I am closing the issue, but you can advise if there could have been some configuration to avoid this code change..

**Comment by mkhare** [comment]
[plugins.txt](https://github.com/Yakifo/amqtt/files/6200669/plugins.txt)
