### ISSUE TITLE
New release

### ISSUE THREAD

**Issue by fabaff** [Yakifo/amqtt#65]
It would be nice to have a new release that includes https://github.com/Yakifo/amqtt/pull/64. Would allow to update distribution packages which out patching.

Thanks

**Comment by fabaff** [comment]
The latest `websockets` is 9.1 in the meantime and this release is fixing a [authentication vulnerability](https://websockets.readthedocs.io/en/stable/changelog.html) which was introduced with 8.0.

**Comment by FlorianLudwig** [comment]
@fabaff new version released. Now compatible with websockets `9.x`

**Comment by fabaff** [comment]
Thank you
