### ISSUE TITLE
DeprecationWarning: The loop argument is deprecated since Python 3.8, and scheduled for removal in Python 3.10.

### ISSUE THREAD

**Issue by Morgloz** [Yakifo/amqtt#77]
I was doing some unit testing for some code that uses the amqtt.client module and this warning showed up two times.
This are the exact spots:

`/home/user/.local/lib/python3.8/site-packages/amqtt/client.py:119: DeprecationWarning: The loop argument is deprecated since Python 3.8, and scheduled for removal in Python 3.10.
  self._connected_state = asyncio.Event(loop=self._loop)`

And

`/home/user/.local/lib/python3.8/site-packages/amqtt/client.py:120: DeprecationWarning: The loop argument is deprecated since Python 3.8, and scheduled for removal in Python 3.10.
  self._no_more_connections = asyncio.Event(loop=self._loop)`

I'm using the 0.10.0 version.

**Comment by jonatanolofsson** [comment]
3.10 is here, and this causes an exception. Could you please prioritize this issue now?

**Comment by jonatanolofsson** [comment]
Solved by PR #84

**Comment by FlorianLudwig** [comment]
This is now merged and the CI also checks with Python 3.10.
