### ISSUE TITLE
Support websockets 10.0

### ISSUE THREAD

**Issue by mweinelt** [Yakifo/amqtt#78]
The websockets library released version 10.0 a month ago. As a distro we would like to keep up with the latest packages and amqtt seems to pin websockets<10. Is there any reason for this or can the pin be relaxed? Thanks for your time!

https://github.com/aaugustin/websockets/releases/tag/10.0

**Comment by FlorianLudwig** [comment]
The pinning is older than the release of the library.

The update from 8 -> 9 did break amqtt. To avoid such break for our users we pin all our dependencies to minor version updates only. We currently do not test against websockets `10.*`

**Comment by HerrMuellerluedenscheid** [comment]
Started addressing that in #80

**Comment by HerrMuellerluedenscheid** [comment]
Resolved in #80
